// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdvancementCard: typeof import('./src/components/AdvancementCard.vue')['default']
    AdvancementIcon: typeof import('./src/components/AdvancementIcon.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    IPhCoffee: typeof import('~icons/ph/coffee')['default']
    IPhGithubLogo: typeof import('~icons/ph/github-logo')['default']
    IPhLightbulbFilament: typeof import('~icons/ph/lightbulb-filament')['default']
    IPhUploadSimpleFill: typeof import('~icons/ph/upload-simple-fill')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Progress: typeof import('./src/components/Progress.vue')['default']
    Upload: typeof import('./src/components/Upload.vue')['default']
  }
}
