// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdvancementIcon: typeof import('./src/components/AdvancementIcon.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    IPhUploadSimpleFill: typeof import('~icons/ph/upload-simple-fill')['default']
    Upload: typeof import('./src/components/Upload.vue')['default']
  }
}
